version: "3.3"

services:
    symfony:
        build: docker/symfony
        volumes:
            - .:/app
        command: "/usr/local/bin/symfony server:start --port 8080"
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
