index:
   path: /
   controller: App\Controller\GameController::new
game:
   path: /game
   methods: GET
   controller: App\Controller\GameController::show

replace:
   path: /game/replacepuck
   methods: POST
   controller: App\Controller\GameController::replacePuck

tilt:
   path: /game
   methods: POST
   controller: App\Controller\GameController::tilt
