index:
   path: /
   controller: App\Controller\GameController::new
game:
   path: /game
   controller: App\Controller\GameController::show

game_action:
   path: /game
   methods: POST
   controller: App\Controller\GameController::action
