index:
   path: /
   controller: App\Controller\GameController::new

replace:
   path: /game/{id}/replacepuck
   methods: POST
   controller: App\Controller\GameController::replacePuck

tilt:
   path: /game/{id}/tilt
   methods: POST
   controller: App\Controller\GameController::tilt

game:
   path: /game/{id}
   methods: GET
   controller: App\Controller\GameController::show
